LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := gcam
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := DMGC7.3.020ver.4.4.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT)/priv-app
LOCAL_OVERRIDES_PACKAGES := com.android.camera2 Snap Camera2 Camera
LOCAL_DEX_PREOPT := false
include $(BUILD_PREBUILT)
